version: '3.9'
services:
  etcd:
    ports:
      - "2379:2379"
    image: quay.io/coreos/etcd:v3.5.6
    command: etcd --initial-cluster-state new --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://127.0.0.1:2379
